# This message is obfuscated, you'll have to run 'make' to see it!

X1 := c
X2 := p
X3 := a
X4 := m
X5 := -
X6 := n
X7 := o
X8 := y

Y1 := ${X4}
Y2 := ${X6}
Y3 := ${X1}
Y4 := ${X2}
Y5 := ${X5}
Y6 := ${X8}
Y7 := ${X3}
Y8 := ${X7}

hi:
	$(info Hello)

say_flag:
	$(info The flag is: ${Y4}${Y7}${Y3}${Y5}${Y1}${Y7}${Y2})
